[phases.setup]
nixPkgs = ["nodejs_24"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = [
  "npm run build",
  "cp -r public .next/standalone/public",
  "mkdir -p .next/standalone/.next",
  "cp -r .next/static .next/standalone/.next/static"
]

[start]
cmd = "node .next/standalone/server.js"
